openapi: '3.0.1'
info:
  title: 'hello-20210330'
  version: '2021-03-30T02:24:51Z'
paths:
  /hello:
    get:
      parameters:
        - name: 'accessToken'
          in: 'query'
          required: true
          schema:
            type: 'string'
      responses:
        '200':
          description: '200 response'
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: 'string'
          content: {}
      security:
        - cognito-user-pool-auth: []
      x-amazon-apigateway-request-validator:
        "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        type: 'aws'
        uri:
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloFunction.Arn}/invocations'
        httpMethod: 'POST'
        responses:
          default:
            statusCode: '200'
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
        #requestTemplates:
        #  application/json: '{ }'
        passthroughBehavior: 'when_no_templates'
        contentHandling: 'CONVERT_TO_TEXT'
components:
  schemas:
    Empty:
      title: 'Empty Schema'
      type: 'object'
  securitySchemes:
    cognito-user-pool-auth:
      type: 'apiKey'
      name: 'Authorization'
      in: 'header'
      x-amazon-apigateway-authtype: 'cognito_user_pools'
      x-amazon-apigateway-authorizer:
        type: 'cognito_user_pools'
        providerARNs:
          - Fn::Sub: '${UserPool.Arn}'
x-amazon-apigateway-request-validators:
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false
