# Be sure to set a corresponding stackname in samconfig.toml

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  A simple authentication and authorization example

Resources:
  HelloApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: 'hello-20210330'
      #!!! Intrinsic functions are not supported in external OpenApi files referenced by DefinitionUri
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './hello-api.yaml'
      StageName: Test
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        # The format must include at least $context.requestId
        # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-stage-accesslogsetting.html
        #Other formats to include later
        #  "authorizeError":"$context.authorize.error",
        #  "authorizeStatus":"$context.authorize.status",
        #  "authorizerSub":"$context.authorizer.claims.sub",
        #  "authorizerError":"$context.authorizer.error",
        #  "authorizerStatus":"$context.authorizer.status",
        #  "authenticateStatus":"$context.authenticate.status",
        # Make sure you have all lines at same indentation so that ">-" removes newlines.
        Format: >-
          { 
          "requestId":"$context.requestId",
          "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller",
          "user":"$context.identity.user",
          "requestTime":"$context.requestTime",
          "httpMethod":"$context.httpMethod",
          "resourcePath":"$context.resourcePath",
          "status":"$context.status",
          "protocol":"$context.protocol",
          "responseLength":"$context.responseLength",
          "integrationError":"$context.integration.error",
          "integrationStatus":"$context.integration.integration.status"
          }

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hello
      CodeUri: hello/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 3
      MemorySize: 128
      Role: !GetAtt LambdaRole.Arn
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref HelloApi

  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hello-20210330

  LambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup

  ApiGatewayLogGroup:
    # This is a Cloud Formation type
    Type: AWS::Logs::LogGroup

  ## An account for this API and corresponding role are required to enable CloudWatch integration.
  Account:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-account.html
  CloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - >-
          arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt LambdaFunctionLogGroup.Arn
        - PolicyName: s3
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action: s3:PutObject
                Resource: !Sub '${HelloBucket.Arn}/*'

  UserPool:
    Type: 'AWS::Cognito::UserPool'
    Properties:
      UserPoolName: 'HelloUserPool20210330'
      # Schema:
      #   - Name: email
      #     Required: true
      #     Mutable: true
      # AdminCreateUserConfig:
      #   AllowAdminCreateUserOnly: true

  UserPoolClient:
    Type: 'AWS::Cognito::UserPoolClient'
    Properties:
      ClientName: 'hello-web-client'
      GenerateSecret: false
      ExplicitAuthFlows:
        ['ALLOW_USER_PASSWORD_AUTH', 'ALLOW_REFRESH_TOKEN_AUTH']
      PreventUserExistenceErrors: 'ENABLED'
      UserPoolId: !Ref UserPool
